spring:
  cloud:
    gateway:
      routes:
        - id: usermanagement-service
          uri: lb://USERMANAGEMENT
          predicates:
            - Path=/user-management/**
          filters:
            - StripPrefix=1
